# Generated by Django 3.0.7 on 2020-06-22 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='date_joined',
            new_name='Date_joined',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='person_name',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='video_name',
            new_name='Video',
        ),
    ]
